chunk_params <- function(){
  ###############################################################################
  ###############################################################################  
  
  #############
  ##### Data  
  #############
  gov_bonds_so <- 	0.1185	     #Kenyan interest on sovereign debt - Central Bank of Kenya
  inflation_so <-  0.02          #Kenyan inflation rate - World Bank Development Indicators
  wage_ag_so <- 	11.84	         #Mean hourly wage rate (KSH) - Suri 2011
  wage_ww_so <- 	14.5850933     #Control group hourly wage, ww (cond >=10 hrs per week) - Table 4, Panel B
  profits_se_so <- 1766          #Control group monthly self-employed profits - Table 4, Panel A  FIX: MOST REFERENCES FROM TABLE 4 ARE TABLE 3
  hours_se_cond_so <- 38.1       #Control group weekly self-employed hours, conditional on hrs >0 - Table D13, Panel D
  hours_ag_so <- 8.3             #Control group hrs per week, agriculture - Table 4, Panel D
  hours_ww_so <- 6.9             #Control group hrs per week, working for wages - Table 4, Panel B
  hours_se_so <- 3.3             #Control group hrs per week, self-employment - Table 4, Panel A
  ex_rate_so <- 85               #Exchange Rate - Central Bank of Kenya
  growth_rate_so <- 1.52/100     #Per-capita GDP growth, 2002-2011 (accessed 1/29/13) -	World Bank - see notes
  coverage_so  <- 0.681333333    # (R) Fraction of treated primary school students within 6 km - from W@W - see note
  tax_so <- 0.16575              #ADD INFO!
  unit_cost_local_so <- 43.66    #Deworm the World
  years_of_treat_so <- 2.41      #Additional Years of Treatment - Table 1, Panel A
  
  costs_so <- 1
  counts_so <- 1

  # costs data FIX WD LATER
  df_costs_so <- read_excel("data_temp/DtW Cost per Child Data.xlsx",
                            sheet = "DtW Costs")
  # crosswalk data on region and country
  df_costs_cw_so <- read_excel("data_temp/DtW Cost per Child Data.xlsx",
                               sheet = "state_country")
  
  # data on number of treated children
  df_counts_so <- read_excel("data_temp/DtW Cost per Child Data.xlsx",
                             sheet = "DtW Treatment #s")
  
  #############
  ##### Research
  #############    
  lambda1_so <- c(3.49, 0)            #Hrs per week increase for men and women CONFIRM
  lambda2_so <- 10.2                  #Externality effect (proportional) - Table 3, Panel B
  lambda1_new_so <- c(87, 83, 81)     # Direct treatment effect on earnings. From tables generated by Michelle on 10/4/1
  lambda1_new_sd_so <- c(43, 83, 172)  # ADD SOURCE
  
  q_full_so <- 0.75              #Take up rates with full subsidy. From Miguel and Kremmer (2007)
  q_zero_so <- 0                 #Take up rates with zero subsidy. From Miguel and Kremmer (2007)
  delta_ed_so <- c(-0.00176350949079451, 0.00696052250263997, 0.0258570306763183,     # (Delta E) Additional direct seconday schooling increase (from Joan)
                   0.0239963665555466, 0.027301406306074, 0.0234125454594173,
                   0.0279278879439199, 0.00647044449446303, 0.00835739437790601)                                     
  delta_ed_so <- cbind(delta_ed_so, 1999:2007)
  delta_ed_ext_so <- c(-0.0110126908021048,	0.0140448546741008,	-0.0034636291545585,  #Additional externality secondary schooling increase (from Joan)
                       0.0112940214439477,	0.0571608179771775,	-0.0560546793186931,
                       0.0558284756343451,	0.1546264843901160,	0.0055961489945619)
  delta_ed_ext_so <- cbind(delta_ed_ext_so, 1999:2007)    
  include_ext_so <- TRUE
  alpha_0_so <- 1 #0.77
  alpha_r_so <- 1 #0.15
  
  #############
  ##### Guess work   
  #############
  periods_so <- 50               #Total number of periods to forecast wages
  time_to_jm_so <- 10            #Time from intial period until individual join the labor force
  coef_exp_so <- c(0, 0)         #Years of experience coefficients (1-linear, 2-cuadratic)	- see notes
  teach_sal_so <- 5041           #Yearly secondary schooling compensation	5041 - from ROI materials
  teach_ben_so <- 217.47         #Yearly secondary schooling teacher benefits	217.47
  n_students_so <- 45            #Average pupils per teacher	45
  
  staff_time_so <- 0.3           #Added Deworming costs due to goverment staff time
  run_sim_so <- FALSE
  main_run_so <- FALSE

  return( sapply( ls(pattern= "_so\\b"), function(x) get(x)) )
  
  ###############################################################################
  ###############################################################################  
}
invisible( list2env(chunk_params(),.GlobalEnv) )
chunk_policy_est <- function(){
  ###############################################################################
  ###############################################################################  
  
  CEA_pe_f <- function(benefits_var = 1, fudging_var = 0, costs_var = 1) {
    ( benefits_var * ( 1 + fudging_var ) ) / costs_var
  }
  RCEA_pe_f <- function(CEA_var = 1, CEA_cash_var = 1){
    CEA_var / CEA_cash_var
  }
  
  NPV_pe_f <- function(benefits_var = 1, costs_var = 1){
    benefits_var - costs_var
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("CEA_pe_f" = CEA_pe_f,
              "RCEA_pe_f" = RCEA_pe_f,
              "NPV_pe_f" = NPV_pe_f))
}
invisible( list2env(chunk_policy_est(),.GlobalEnv) )
chunk_cost1 <- function(){
  ###############################################################################
  ###############################################################################  
  
  costs1_f <- function(country_w_var = 1, country_cost_var = 1) {
    sum(country_w_var * country_cost_var)
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("costs1_f" = costs1_f))
}
invisible( list2env(chunk_cost1(),.GlobalEnv) )
chunk_cost1_inp <- function(){
  ###############################################################################
  ###############################################################################  
  
  costs1_costs_f <- function(df_costs_var = df_costs_so,
                             df_costs_cw_var = df_costs_cw_so,
                             staff_time_var = staff_time_so){
    # Add country
    df_costs_var <- df_costs_cw_var %>%
      right_join(df_costs_var, by = "Country/State") %>%
      select(-Country.y) %>% rename(Country = Country.x) %>%
      mutate(Country = tolower(Country))
    
    # values for last year with cost information
    df_costs_last <- df_costs_var %>%
      group_by(Country) %>%
      summarise("last_year" = max(Year)) %>%
      right_join(df_costs_var, by = "Country") %>%
      filter(Year == last_year)    
    
    # summing across payers and regions (last equation)
    costs_by_item_temp <- df_costs_last %>%
      filter(Payer != "Total") %>%
      group_by(Country, `Program Area`) %>%
      summarise("costs_by_region" = sum(suppressWarnings( as.numeric(Cost) ), na.rm = TRUE))
    
    #sum across country/state and multiply by delta
    country_cost <- costs_by_item_temp %>%
      group_by(Country) %>%
      summarise("costs_by_country" = sum(costs_by_region) * (1 + staff_time_var))  
    
    return( list("cost_data" = country_cost) )
  }
  
  costs1_counts_f <- function(df_counts_var = df_counts_so,
                              df_costs_cw_var = df_costs_cw_so){
    # Add country
    df_counts_var <- df_costs_cw_var %>%
      right_join(df_counts_var, by = "Country/State") %>%
      mutate(Country = tolower(Country))
    
    # values for last year with cost information
    df_counts_last <- df_counts_var %>%
      group_by(Country) %>%
      summarise("last_year" = max(Year)) %>%
      right_join(df_counts_var, by = "Country") %>%
      filter(Year == last_year)    
    
    c_counts <- df_counts_last %>%
      group_by(Country, Year) %>%
      summarise("total" = sum(`# dewormed`))
    
    return( list("counts_data" = c_counts) )
  }
  
  costs1_ratios_in_f <- function(counts_var = costs1_counts_f()$counts_data,
                                 costs_var = costs1_costs_f()$cost_data){
    # create country weight
    c_weights <- counts_var %>% ungroup() %>%
      mutate(country_w = total / sum(total))
    
    # Compute the per capita cost for each country
    ratios_data <- costs_var %>%
      left_join(c_weights, by = "Country") %>%
      mutate("per_cap" = costs_by_country / total)
    
    return( list("ratios_data" = ratios_data) )
  }
  
  ###############################################################################
  ###############################################################################  
  return( list("costs1_costs_f" = costs1_costs_f,
               "costs1_counts_f" = costs1_counts_f,
               "costs1_ratios_in_f" = costs1_ratios_in_f) )
}
invisible( list2env(chunk_cost1_inp(),.GlobalEnv) )
chunk_cost2 <- function(){
  ###############################################################################
  ###############################################################################  
  
  cost2_f <- function(periods_var = periods_so, delta_ed_var = delta_ed_final_in,
                      interest_r_var = interest, cost_of_schooling_var = cost_per_student_in,
                      s1_var = 0, q1_var = 0, s2_var = s2_in, q2_var = q2_in) {
    index_t <- 0:periods_var
    delta_ed_s <- c(0, delta_ed_var, rep(0,41))
    sum( ( 1 / (1 + interest_r_var) )^index_t *
           delta_ed_s * cost_of_schooling_var) +
      (s2_var * q2_var  - s1_var * q1_var)
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("cost2_f" = cost2_f))    # Try to return only functions
}
invisible( list2env(chunk_cost2(),.GlobalEnv) )
chunk_edcosts <- function(){
  ###############################################################################
  ###############################################################################    
  
  cost_per_student_f <- function(teach_sal_var = teach_sal_so,
                                 teach_ben_var = teach_ben_so,
                                 n_students_var = n_students_so) {
    (teach_sal_var + teach_ben_var) / n_students_var
  }
  
  delta_ed_final_f <- function(include_ext_var = include_ext_so, delta_ed_var = delta_ed_so,
                               delta_ed_ext_var = delta_ed_ext_so){
    if (include_ext_var == TRUE){
      delta_ed_final_in <-  delta_ed_ext_var[,1] + delta_ed_var[,1]
    }else{
      delta_ed_final_in <- delta_ed_var[,1]
    }
    return(delta_ed_final_in)
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("cost_per_student_f" = cost_per_student_f,
              "delta_ed_final_f" = delta_ed_final_f))
}
invisible( list2env(chunk_edcosts(),.GlobalEnv) )
chunk_unit_costs2 <- function(){
  ###############################################################################
  ###############################################################################  
  
  s2_f <- function(unit_cost_local_var = unit_cost_local_so,
                   ex_rate_var = ex_rate_so, years_of_treat_var = years_of_treat_so) {
    ( unit_cost_local_var / ex_rate_var ) * years_of_treat_var
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("s2_f" = s2_f) )
}
invisible( list2env(chunk_unit_costs2(),.GlobalEnv) )
chunk_benefits <- function(){
  ###############################################################################
  ###############################################################################  
  
  pv_benef_f <- function(earnings_var = earnings_in, interest_r_var = interest_in,
                         periods_var = periods_so) {
    index_t <- 0:periods_var
    res1 <- sum( ( 1 / (1 + interest_r_var) )^index_t * earnings_var )
    return(res1)   
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("pv_benef_f" = pv_benef_f))
}
invisible( list2env(chunk_benefits(),.GlobalEnv) )
chunk_interest <- function(){
  ###############################################################################
  ###############################################################################  
  
  interest_f <- function(gov_bonds_var = gov_bonds_so , inflation_var = inflation_so) {  
    interest_in = gov_bonds_var - inflation_var
    return(list("interest_in" = interest_in))
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("interest_f" = interest_f))
}

invisible( list2env(chunk_interest(),.GlobalEnv) )
chunk_earnings1 <- function(){
  ###############################################################################
  ###############################################################################  
  
  earnings1_f <- function(wage_var = wage_in,
                          lambda1_var = lambda1_so,
                          lambda2_var = lambda2_so,
                          saturation_var = saturation, coverage_var) {  
    res1 <- wage_var * ( lambda1_var + saturation_var * lambda2_var / coverage_var )
    return(res1)
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("earnings1_f" = earnings1_f))
}

invisible( list2env(chunk_earnings1(),.GlobalEnv) )
chunk_wages <- function(){
  ################################################################################
  ################################################################################  
  #close to value from spreadsheet (Assumps&Panel A Calcs!B137 = 0.1481084),
  #but I suspect diff due to computational precision
  
  wage_0_mo_f <- function(wage_ag_var, wage_ww_var, profits_se_var, hours_se_cond_var,
                          hours_ag_var, hours_ww_var, hours_se_var, ex_rate_var) {
    experience_aux <- 0:periods_so - time_to_jm_so
    wage_se <- profits_se_var / (4.5 * hours_se_cond_var)
    wage_ls <- c(wage_ag_var, wage_ww_var, wage_se)
    alpha_ls <- c(hours_ag_var, hours_ww_var, hours_se_var) / sum( c(hours_ag_var, hours_ww_var, hours_se_var) )
    res1 <- 1/ex_rate_var * sum( wage_ls * alpha_ls )
    return(res1)
  }
  
  wage_t_mo_f <- function(wage_0_var,
                          growth_rate_var,
                          coef_exp1_var,
                          coef_exp2_var) {
    experience_aux <- 0:periods_so - time_to_jm_so
    res1 <- 52 * wage_0_var *( ( 1 + growth_rate_var )^experience_aux ) *
      ( 1 + coef_exp1_var * experience_aux + coef_exp2_var * experience_aux^2 ) *
      ifelse(0:periods_so >= time_to_jm_so, 1, 0)
    return(res1)
  }
  
  wage_0_mo <- wage_0_mo_f(wage_ag_var = wage_ag_so,  
                           wage_ww_var = wage_ww_so,
                           profits_se_var = profits_se_so,
                           hours_se_cond_var = hours_se_cond_so,  
                           hours_ag_var = hours_ag_so,
                           hours_ww_var = hours_ww_so,
                           hours_se_var = hours_se_so,
                           ex_rate_var = ex_rate_so)  
  
  #close to value from spreadsheet (Calcs-Table 5!N21.. = 7.701634678),
  #but I suspect diff due to computational precision
  wage_t_mo <- wage_t_mo_f(wage_0_var = wage_0_mo,
                           growth_rate_var = growth_rate_so,
                           coef_exp1_var = coef_exp_so[1],
                           coef_exp2_var = coef_exp_so[2])
  
  ################################################################################
  ################################################################################
  return(list("wage_0_mo_f" = wage_0_mo_f, "wage_0_mo" = wage_0_mo,
              "wage_t_mo_f" = wage_t_mo_f, "wage_t_mo" = wage_t_mo))
}

invisible( list2env(chunk_wages(),.GlobalEnv) )
chunk_new_earnings <- function(){
  ###############################################################################
  ###############################################################################  
  
  earnings2_f <- function(t_var = 1,
                          lambda1k1_var = lambda1_new_so[1],
                          lambda1k2_var = lambda1_new_so[2],
                          lambda1k3_var = lambda1_new_so[3]) {
    1*(10 <= t_var & t_var < 15) * lambda1k1_var +
      1*(15 <= t_var & t_var < 20) * lambda1k2_var +
      1*(20 <= t_var) * lambda1k3_var
  }
  
  ###############################################################################
  ###############################################################################             
  return(list("earnings2_f" = earnings2_f))
}

invisible( list2env(chunk_new_earnings(),.GlobalEnv) )
chunk_lambdas<- function(){
  ###############################################################################
  ###############################################################################    
  
  lambda1_in_f <- function(lambda1_var = lambda1_so) {
    rep(0.5 * lambda1_var[1] + 0.5 *lambda1_var[2], 2)
  }
  
  lambda_r_f <- function(lambda1_var = lambda1_in_f(), alpha_0_var = alpha_0_so,
                         alpha_r_var=alpha_r_so){
    lambda1_eff_temp <- lambda1_var / alpha_0_var
    return( lambda1_eff_temp * alpha_r_var )
  }  
  
  lambda2_in_f <- function(lambda2_var = lambda2_so){
    rep(lambda2_var, 2)
  }
  
  ##############################################################################
  ###############################################################################  
  return(list("lambda_r_f" = lambda_r_f,     
              "lambda1_in_f" = lambda1_in_f,
              "lambda2_in_f" = lambda2_in_f ) )
}
invisible( list2env(chunk_lambdas(),.GlobalEnv) )
# - inputs: coverage_so, q_full_so, q_zero_so
# - outputs: saturation_in
chunk_coverage <- function(){
  ###############################################################################
  ###############################################################################  
  
  saturation_in_f <- function(coverage_var = coverage_so, q_full_var = q_full_so,
                              q_zero_var = q_zero_so){
    saturation_in <- coverage_so * q_full_so + ( 1 - coverage_so ) * q_zero_so
    return(list("saturation_in" = saturation_in))
  }
  
  ###############################################################################
  ###############################################################################  
  return(list("saturation_in_f" = saturation_in_f))    # Try to return only functions
}
invisible( list2env(chunk_coverage(),.GlobalEnv) )

#unit test function
unit_test <- function(to_test_var, original_var, main_run_var = TRUE){
  if (main_run_var == TRUE) {
    if (length(to_test_var) > 1) {
      fails_test <- ( abs(sd(to_test_var) - original_var) > 0.0001 )
      text_val <- sd(to_test_var)
    } else {
      fails_test <- ( abs(to_test_var - original_var) > 0.0001 )
      text_val <- to_test_var
    }
    if (fails_test) {
      print(paste("Output has change at", deparse(substitute(to_test_var) ), " to ", text_val) )
    }
  }
}


one_run <-
  function(main_run_var1 = main_run_so,
           run_sim_var = run_sim_so,
           wage_ag_var1 = wage_ag_so,
           wage_ww_var1 = wage_ww_so,
           profits_se_var1 = profits_se_so,
           hours_se_cond_var1 = hours_se_cond_so,
           hours_ag_var1 = hours_ag_so,
           hours_ww_var1 = hours_ww_so,
           hours_se_var1 = hours_se_so,
           ex_rate_var1 = ex_rate_so,
           growth_rate_var1 = growth_rate_so,
           coef_exp_var1 = coef_exp_so[1], coef_exp2_var1 = coef_exp_so[2],
           lambda1_var1 = lambda1_in_f(lambda1_var = lambda1_so),
           alpha_0_var1 = alpha_0_so,
           alpha_r_var1 = alpha_r_so,
           lambda2_var1 = lambda2_so,
           coverage_var1 = coverage_so,
           q_full_var1 = q_full_so,
           q_zero_var1 = q_zero_so,
           lambda1_new_var1 = lambda1_new_so,
           gov_bonds_var1 = gov_bonds_so,
           inflation_var1 = inflation_so,
           df_costs_var1 = df_costs_so,
           df_costs_cw_var1 = df_costs_cw_so,
           staff_time_var1 = staff_time_so,
           df_counts_var1 = df_counts_so,
           delta_ed_var1 = delta_ed_so,
           delta_ed_ext_var1 = delta_ed_ext_so,
           teach_sal_var1 = teach_sal_so,
           teach_ben_var1 = teach_ben_so,
           n_students_var1 = n_students_so,
           unit_cost_local_var1 = unit_cost_local_so,
           years_of_treat_var1 = years_of_treat_so,
           tax_var1 = tax_so,
           periods_var1 = periods_so) {
    
    
    ####------------ Inputs for wage_t ---------------------------------------------
    wage_0_in <- wage_0_mo_f(wage_ag_var = wage_ag_var1, wage_ww_var = wage_ww_var1,
                             profits_se_var = profits_se_var1, hours_se_cond_var = hours_se_cond_var1,  
                             hours_ag_var = hours_ag_var1, hours_ww_var = hours_ww_var1,
                             hours_se_var = hours_se_var1, ex_rate_var = ex_rate_var1)
    unit_test(wage_0_in, 0.1481084, main_run_var = main_run_var1)
    ###---------- Inputs for earnings1_f -------------------------------------------
    wage_t_in <- wage_t_mo_f(wage_0_var = wage_0_in, growth_rate_var = growth_rate_var1,
                             coef_exp1_var = coef_exp_var1, coef_exp2_var = coef_exp_var1)
    
    lambda1_in <- lambda_r_f(lambda1_var = lambda1_in_f(lambda1_var = lambda1_var1),
                             alpha_0_var = alpha_0_var1, alpha_r_var = alpha_r_var1)
    
    lambda2_in <- lambda2_in_f(lambda2_var = lambda2_var1)
    
    saturation_in <- as.numeric(saturation_in_f(coverage_var = coverage_var1,
                                                q_full_var = q_full_var1,
                                                q_zero_var = q_zero_var1) )
    unit_test(wage_t_in, 4.572308, main_run_var = main_run_var1)
    # ADD UNIT TEST FOR SATURATION AN LAMBDAS    
    
    ###------------ Inputs for earnings2_f------------------------------------------
    lambda1_new_in <- lambda_r_f(lambda1_var = lambda1_new_var1,
                                 alpha_0_var = alpha_0_var1,
                                 alpha_r_var = alpha_r_var1)
    #ADD UNIT TEST FOR LAMBDAS    
    
    ##------------ Inputs for pv_benef_f -------------------------------------------
    # earnings1
    earnings_in_no_ext <- earnings1_f(wage_var = wage_t_in, lambda1_var = lambda1_in[1],
                                      lambda2_var = 0, saturation_var = saturation_in,
                                      coverage_var = coverage_var1)
    earnings_in_yes_ext <- earnings1_f(wage_var = wage_t_in, lambda1_var = lambda1_in[1],
                                       lambda2_var = lambda2_in[1], saturation_var = saturation_in,
                                       coverage_var = coverage_var1)
    
    # earnings2
    earnings_in_no_ext_new <- earnings2_f(t_var = 0:50,
                                          lambda1k1_var = lambda1_new_in[1],
                                          lambda1k2_var = lambda1_new_in[2],
                                          lambda1k3_var = lambda1_new_in[3])
    # ADD UNIT TEST
    interest_in <- as.numeric( interest_f(gov_bonds_var = gov_bonds_var1,
                                          inflation_var = inflation_var1) )
    unit_test(earnings_in_no_ext, 7.978677, main_run_var = main_run_var1)
    unit_test(earnings_in_yes_ext, 42.95683, main_run_var = main_run_var1)
    unit_test(interest_in, 0.0985, main_run_var = main_run_var1)
    
    ###------------- Inputs for costs1_ratios_in_f----------------------------------
    costs1_counts_in <- costs1_counts_f(df_counts_var = df_counts_var1,
                                        df_costs_cw_var = df_costs_cw_var1)$counts_data
    costs1_costs_in <- costs1_costs_f(df_costs_var = df_costs_var1,
                                      df_costs_cw_var = df_costs_cw_var1,
                                      staff_time_var = staff_time_var1)$cost_data
    # ADD UNIT TEST
    # The following section only runs when running the simulations (later add: a skip to load the data only once)
    if (run_sim_var ==  TRUE) {
      costs1_counts_sim <- costs1_counts_in %>%
        mutate("total" = rnorm(n = 1, mean = total, sd = 0.1 * total))
      costs1_costs_sim <- costs1_costs_in %>% group_by(Country) %>%
        mutate("costs_by_country" = rnorm(n = 1, mean = costs_by_country,
                                          sd = 0.1 * costs_by_country))
    } else {
      costs1_counts_sim <- NA
      costs1_costs_sim <- NA
    }
    
    ##-------------- Inputs for costs1_f--------------------------------------------
    if (run_sim_var == TRUE) {
      costs1_country <-  costs1_ratios_in_f(counts_var = costs1_counts_sim,
                                            costs_var =  costs1_costs_sim)
    } else {
      costs1_country <-  costs1_ratios_in_f(counts_var = costs1_counts_in,
                                            costs_var =  costs1_costs_in)
      unit_test(unlist(costs1_country$ratios_data$costs_by_country),  6880801.84046596, main_run_var = main_run_var1)
    }
    
    ##-------------- Inputs for costs2_f--------------------------------------------
    # Make explicit non-function inputs:
    delta_ed_final_in <- delta_ed_final_f(include_ext_var = FALSE,
                                          delta_ed_var = delta_ed_var1,
                                          delta_ed_ext_var = delta_ed_ext_var1)
    unit_test(delta_ed_final_in, 0.01134819, main_run_var = main_run_var1)
    
    delta_ed_final_in_x <- delta_ed_final_f(include_ext_var = TRUE,
                                            delta_ed_var = delta_ed_var1,
                                            delta_ed_ext_var = delta_ed_ext_var1)
    unit_test(delta_ed_final_in_x,  0.05911765, main_run_var = main_run_var1)
    
    interest_in <- as.numeric( interest_f(gov_bonds_var = gov_bonds_var1,
                                          inflation_var = inflation_var1) )
    unit_test(interest_in, 0.0985, main_run_var = main_run_var1)
    
    cost_per_student_in <-  cost_per_student_f(teach_sal_var = teach_sal_var1,
                                               teach_ben_var = teach_ben_var1,
                                               n_students_var = n_students_var1)
    unit_test(cost_per_student_in,  116.8549, main_run_var = main_run_var1)
    
    s2_in <- s2_f(unit_cost_local_var = unit_cost_local_var1,
                  ex_rate_var = ex_rate_var1, years_of_treat_var = years_of_treat_var1)
    unit_test(s2_in, 1.237889, main_run_var = main_run_var1)
    #--------------- Inputs for NPV_pe_f, CEA_pe_f and RCEA_pe_f--------------------
    # Make explicit non-function inputs:
    #Benefits:
    #Baird w/tax and no externalities (no ext)
    pv_benef_tax_nx_in <- pv_benef_f(earnings_var = earnings_in_no_ext * tax_var1,
                                     interest_r_var = interest_in, periods_var = periods_var1)
    unit_test(pv_benef_tax_nx_in, 11.02849, main_run_var = main_run_var1)
    #Baird w/t and ext
    pv_benef_tax_yx_in <- pv_benef_f(earnings_var = earnings_in_yes_ext * tax_var1,
                                     interest_r_var = interest_in, periods_var = periods_var1)
    unit_test(pv_benef_tax_yx_in, 59.37686, main_run_var = main_run_var1)
    #Baird all and no
    pv_benef_all_nx_in <- pv_benef_f(earnings_var = earnings_in_no_ext,
                                     interest_r_var = interest_in, periods_var = periods_var1)
    unit_test(pv_benef_all_nx_in, 66.5368686659935, main_run_var = main_run_var1)
    #Baird all and ext
    pv_benef_all_yx_in <- pv_benef_f(earnings_var = earnings_in_yes_ext,
                                     interest_r_var = interest_in, periods_var = periods_var1)
    unit_test(pv_benef_all_yx_in, 358.231450496853, main_run_var = main_run_var1)
    
    #KLPS4 w/t and no ext
    pv_benef_tax_new <- pv_benef_f(earnings_var = earnings_in_no_ext_new * tax_var1,
                                   interest_r_var = interest_in, periods_var = periods_var1)
    # ADD UNIT TEST
    # KLPS4 all and no ext
    pv_benef_all_new <- pv_benef_f(earnings_var = earnings_in_no_ext_new,
                                   interest_r_var = interest_in, periods_var = periods_var1)
    # ADD UNIT TEST
    
    #Costs
    # costs1: EA costs no externalities
    cost1_in <- costs1_f(country_w_var = costs1_country$ratios_data$country_w,
                         country_cost_var = costs1_country$ratios_data$per_cap)
    unit_test(cost1_in,  0.08480686, main_run_var = main_run_var1)
    # costs2: Baird no externalities
    costs2_in <- cost2_f(periods_var = periods_var1, delta_ed_var = delta_ed_final_in,
                         interest_r_var = interest_in, cost_of_schooling_var = cost_per_student_in,
                         s1_var = 0, q1_var = 0, s2_var = s2_in, q2_var = q_full_var1)
    unit_test(costs2_in, 11.63818, main_run_var = main_run_var1)
    
    # Baird yes externalities
    costs2_in_x <- cost2_f(periods_var = periods_var1, delta_ed_var = delta_ed_final_in_x,
                           interest_r_var = interest_in, cost_of_schooling_var = cost_per_student_in,
                           s1_var = 0, q1_var = 0, s2_var = s2_in, q2_var = q_full_var1)
    unit_test(costs2_in_x,  25.05821, main_run_var = main_run_var1)
    
    return( list( "wage_0_in" = wage_0_in, "wage_t_in" = wage_t_in, "lambda1_in" = lambda1_in,
                  "lambda2_in" = lambda2_in, "saturation_in" = saturation_in,
                  "lambda1_new_in" = lambda1_new_in, "earnings_in_no_ext" = earnings_in_no_ext,
                  "earnings_in_yes_ext" = earnings_in_yes_ext,
                  "earnings_in_no_ext_new" = earnings_in_no_ext_new,
                  "interest_in" = interest_in, "costs1_counts_in" = costs1_counts_in,
                  "costs1_costs_in" = costs1_costs_in, "costs1_counts_sim" = costs1_counts_sim,
                  "costs1_costs_sim" = costs1_costs_sim, "costs1_country" = costs1_country,
                  "delta_ed_final_in" = delta_ed_final_in, "delta_ed_final_in_x" = delta_ed_final_in_x,
                  "cost_per_student_in" = cost_per_student_in, "s2_in" = s2_in,  
                  "pv_benef_tax_nx_in"= pv_benef_tax_nx_in, "pv_benef_tax_yx_in" = pv_benef_tax_yx_in,
                  "pv_benef_all_nx_in" = pv_benef_all_nx_in,
                  "pv_benef_all_yx_in" =  pv_benef_all_yx_in, "pv_benef_tax_new" = pv_benef_tax_new,
                  "pv_benef_all_new" = pv_benef_all_new, "cost1_in" = cost1_in,
                  "costs2_in" = costs2_in, "costs2_in_x" = costs2_in_x) )
  }




invisible( list2env(one_run(),.GlobalEnv) )


policy_estimates <- c("baird1_sim",          
                      "baird2_sim"         , 
                      "baird3_sim"         , 
                      "baird4_sim"         , 
                      "klps4_1_sim"        , 
                      "klps4_2_sim"        , 
                      "ea1_sim"            , 
                      "ea2_sim"            , 
                      "ea3_sim"            , 
                      "cea_no_ext_ea_sim"  , 
                      "rcea_no_ext_ea_sim" ) 

policy_estimates_text <- c(
  "Fiscal effects, 2016(W@W) B & C, no ext", 
  "Fiscal effects, 2016(W@W) B & C, yes ext",  
  "Total effects, 2016(W@W) B & C, no ext",  
  "Total effects, 2016(W@W) B & C, yes ext",  
  "Fiscal effects, 2019(KLPS4) B & 2016(W@W) C, no ext",   
  "Total effects, 2019(KLPS4) B & 2016(W@W) C, no ext",  
  "Total effects, 2016(W@W) B & EA C, no ext",  
  "Total effects, 2016(W@W) B & EA C, ext",  
  "Total effects, 2019(KLPS4) B & EA C, no ext", 
  "CEA for total effects, 2019(KLPS4) B & EA C, no ext",
  "RCEA to cash for total effects, 2019(KLPS4) B & EA C, no ext")