---
title: "Template"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    code_download: true
    collapsed: yes
    keep_md: yes
    number_sections: yes
    smooth_scroll: no
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---
\def\blue{\color{blue}}


```{r setup, include=FALSE} 
# Loading required libraries
list.of.packages <- c("tidyverse", "haven", "here", "kableExtra")

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos= "http://cran.cnr.berkeley.edu/")

lapply(list.of.packages, library, character.only = TRUE)

knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(echo = TRUE)

print_code <- TRUE
``` 


```{r parameters, echo=print_code}
# Do not run data set on git/github until privacy has been cleared
################
##### Data  
################
################
##### Research
################
################
##### Guess work   
################
################
#####  Notes:
################
### Source ---->  Input ----> Model ----> Policy Estimates (output)
###  (_so)        (_in)       (_mo)        (_pe)
### values      functions   functions      values
###             & values    & values
### arguments in functions should used "_var" and functions should "_f"
#invisible( list2env(call_params_f(),.GlobalEnv) )
```


# Key policy estimates for policy makers  

```{r final-output}
```

# Methodology

## Main Equation (the model)

\begin{equation}
y = f(x)
\label{eq:1}
\tag{1}
\end{equation}

```{r test, eval=FALSE}
# - inputs: 
# - outputs: 
chunk_test <- function(){
############################################################################### 
###############################################################################  
  
    somefunction_f <- function(somethinig_var = somethinig_default) {
        somethinig_var
    }
    
############################################################################### 
###############################################################################  
    return(list("somefunction_f" = delta_earnings))    # Try to return only functions
}
invisible( list2env(chunk_test(),.GlobalEnv) )

##### Execute values of the functions above when needed for the text:
somefunction_in <- somefunction_f()
```

## Sub components:

### 1 - Component 1 ("$r$")

```{r comp1,  echo=print_code}
# - inputs: tax_rev_init_mo, top_tax_base_in
# - outputs: total_rev_pe
```
# Main results
```{r main-results,  echo=print_code}
# - inputs: tax_rev_init_mo, top_tax_base_in
# - outputs: total_rev_pe
```


# Montecarlo simulations  
```{r,  echo=print_code}
# Draws
# Compute inputs
# Compute model
# Run sims
```

# Sensitivity Analysis  
