blank_issues_enabled: false
contact_links:
  - name: Email BITSS OPA
    url: fhoces@berkeley.edu
    about: Reach out directly to BITSS.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
